# Generated by Django 4.2.17 on 2024-12-27 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(default='Not Assigned', max_length=100)),
                ('salary', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonus', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('role', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
                ('hire_date', models.DateField()),
            ],
        ),
    ]
