# Generated by Django 4.2.17 on 2024-12-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee_details',
        ),
    ]
